version: '3'

services:
  spark-master:
    container_name: spark-master
    hostname: spark-master
    build:
      context: .
      dockerfile: Dockerfile.spark
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    environment:
      - PYTHONPATH=/opt/spark
    volumes:
      - ./config:/opt/spark/config
      - ./jobs:/opt/spark/jobs
      - ./datasets:/opt/spark/datasets
      - ./requirements.txt:/requirements.txt
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      - code-with-yu

  spark-worker:
    container_name: spark-worker
    hostname: spark-worker
    build:
      context: .
      dockerfile: Dockerfile.spark
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    volumes:
      - ./config:/opt/spark/config
      - ./jobs:/opt/spark/jobs
      - ./datasets:/opt/spark/datasets
      - ./requirements.txt:/requirements.txt
    depends_on:
      - spark-master
    environment:
      - PYTHONPATH=/opt/spark
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - code-with-yu

networks:
  code-with-yu: